[workspace]
resolver = "3"
members = [
    "crates/tesseras-core",
    "crates/tesseras-crypto",
    "crates/tesseras-storage",
    "crates/tesseras-cli",
    "crates/tesseras-net",
    "crates/tesseras-dht",
    "crates/tesseras-daemon",
]

[workspace.package]
edition = "2024"
license = "ISC"
rust-version = "1.85"

[workspace.dependencies]
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
rmp-serde = "1"

# Error handling
thiserror = "2"
anyhow = "1"

# Async
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

# Network
quinn = "0.11"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
rcgen = "0.13"
dashmap = "6"

# Crypto
blake3 = "1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
reed-solomon-erasure = "6"

# Storage
rusqlite = { version = "0.33" }

# CLI
clap = { version = "4", features = ["derive"] }
dialoguer = "0.11"
comfy-table = "7"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

# Misc
dirs = "6"

# Testing
mockall = "0.13"
proptest = "1"
tempfile = "3"

# Internal
tesseras-core = { path = "crates/tesseras-core" }
tesseras-crypto = { path = "crates/tesseras-crypto" }
tesseras-dht = { path = "crates/tesseras-dht" }
tesseras-net = { path = "crates/tesseras-net" }
tesseras-storage = { path = "crates/tesseras-storage" }
