[workspace]
resolver = "3"
members = ["tesseras", "tes", "crates/tesseras-embedded"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "ISC"
repository = "https://git.sr.ht/~ijanc/tesseras"

[workspace.dependencies]
# Domain
tesseras = { path = "tesseras" }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"
rmp-serde = "1"

# Error handling
thiserror = "2"
anyhow = "1"

# Async
tokio = { version = "1", features = ["full"] }

# Crypto
blake3 = "1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
zeroize = { version = "1", features = ["derive"] }
reed-solomon-erasure = "6"

# Network
quinn = "0.11"
rustls = { version = "0.23", features = ["ring", "std"] }
rcgen = "0.13"

# Storage
rusqlite = { version = "0.33", features = ["bundled"] }

# CLI
clap = { version = "4", features = ["derive", "color"] }
indicatif = "0.17"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

# Encoding
hex = "0.4"

# FFI
flutter_rust_bridge = "=2.11.1"

# Misc
dirs = "6"

# Testing
tempfile = "3"
proptest = "1"
