#!/bin/sh
set -e

case $2 in
PRE-INSTALL)
    if ! getent group _tesseras >/dev/null 2>&1; then
        groupadd _tesseras
    fi
    if ! getent passwd _tesseras >/dev/null 2>&1; then
        useradd -g _tesseras -d /var/lib/tesseras \
                -s /sbin/nologin -c "Tesseras daemon" _tesseras
    fi
    ;;
POST-INSTALL)
    install -d -o _tesseras -g _tesseras -m 0750 /var/lib/tesseras
    install -d -o _tesseras -g _tesseras -m 0750 /var/run/tesseras

    echo ""
    echo "To enable and start tesseras:"
    echo "  doas rcctl enable tesd"
    echo "  doas rcctl start tesd"
    echo ""
    ;;
esac

exit 0
