// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1544659011;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'tesseras_embedded',
        ioDirectory: '../../crates/tesseras-embedded/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  IdentityInfo crateApiSimpleCreateIdentity({
    required String name,
    String? avatarPath,
  });

  MemoryInfo crateApiSimpleCreateMemory({
    required String mediaPath,
    String? contextText,
    required String memoryType,
    required String visibility,
    String? locationDescription,
    double? locationLat,
    double? locationLon,
    required List<String> tags,
    required List<String> people,
  });

  IdentityInfo? crateApiSimpleGetIdentity();

  MemoryInfo crateApiSimpleGetMemory({required String hash});

  NetworkStats crateApiSimpleGetNetworkStats();

  ReplicationStatus crateApiSimpleGetReplicationStatus();

  List<MemoryInfo> crateApiSimpleGetTimeline({
    required int offset,
    required int limit,
  });

  Future<void> crateApiSimpleInitApp();

  bool crateApiSimpleNodeIsRunning();

  void crateApiSimpleNodeStart({required String dataDir});

  void crateApiSimpleNodeStop();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  IdentityInfo crateApiSimpleCreateIdentity({
    required String name,
    String? avatarPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          sse_encode_opt_String(avatarPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCreateIdentityConstMeta,
        argValues: [name, avatarPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "create_identity",
        argNames: ["name", "avatarPath"],
      );

  @override
  MemoryInfo crateApiSimpleCreateMemory({
    required String mediaPath,
    String? contextText,
    required String memoryType,
    required String visibility,
    String? locationDescription,
    double? locationLat,
    double? locationLon,
    required List<String> tags,
    required List<String> people,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mediaPath, serializer);
          sse_encode_opt_String(contextText, serializer);
          sse_encode_String(memoryType, serializer);
          sse_encode_String(visibility, serializer);
          sse_encode_opt_String(locationDescription, serializer);
          sse_encode_opt_box_autoadd_f_64(locationLat, serializer);
          sse_encode_opt_box_autoadd_f_64(locationLon, serializer);
          sse_encode_list_String(tags, serializer);
          sse_encode_list_String(people, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_memory_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCreateMemoryConstMeta,
        argValues: [
          mediaPath,
          contextText,
          memoryType,
          visibility,
          locationDescription,
          locationLat,
          locationLon,
          tags,
          people,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateMemoryConstMeta => const TaskConstMeta(
    debugName: "create_memory",
    argNames: [
      "mediaPath",
      "contextText",
      "memoryType",
      "visibility",
      "locationDescription",
      "locationLat",
      "locationLon",
      "tags",
      "people",
    ],
  );

  @override
  IdentityInfo? crateApiSimpleGetIdentity() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_identity_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetIdentityConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetIdentityConstMeta =>
      const TaskConstMeta(debugName: "get_identity", argNames: []);

  @override
  MemoryInfo crateApiSimpleGetMemory({required String hash}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(hash, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_memory_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetMemoryConstMeta,
        argValues: [hash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetMemoryConstMeta =>
      const TaskConstMeta(debugName: "get_memory", argNames: ["hash"]);

  @override
  NetworkStats crateApiSimpleGetNetworkStats() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_network_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetNetworkStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetNetworkStatsConstMeta =>
      const TaskConstMeta(debugName: "get_network_stats", argNames: []);

  @override
  ReplicationStatus crateApiSimpleGetReplicationStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_replication_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetReplicationStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetReplicationStatusConstMeta =>
      const TaskConstMeta(debugName: "get_replication_status", argNames: []);

  @override
  List<MemoryInfo> crateApiSimpleGetTimeline({
    required int offset,
    required int limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(offset, serializer);
          sse_encode_u_32(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGetTimelineConstMeta,
        argValues: [offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTimelineConstMeta => const TaskConstMeta(
    debugName: "get_timeline",
    argNames: ["offset", "limit"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  bool crateApiSimpleNodeIsRunning() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleNodeIsRunningConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNodeIsRunningConstMeta =>
      const TaskConstMeta(debugName: "node_is_running", argNames: []);

  @override
  void crateApiSimpleNodeStart({required String dataDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleNodeStartConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNodeStartConstMeta =>
      const TaskConstMeta(debugName: "node_start", argNames: ["dataDir"]);

  @override
  void crateApiSimpleNodeStop() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleNodeStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleNodeStopConstMeta =>
      const TaskConstMeta(debugName: "node_stop", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  IdentityInfo dco_decode_box_autoadd_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_identity_info(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return IdentityInfo(
      name: dco_decode_String(arr[0]),
      avatarPath: dco_decode_opt_String(arr[1]),
      publicKeyHex: dco_decode_String(arr[2]),
      nodeIdHex: dco_decode_String(arr[3]),
      createdAt: dco_decode_String(arr[4]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MemoryInfo> dco_decode_list_memory_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_memory_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MemoryInfo dco_decode_memory_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return MemoryInfo(
      hash: dco_decode_String(arr[0]),
      tesseraHash: dco_decode_String(arr[1]),
      mediaPath: dco_decode_String(arr[2]),
      context: dco_decode_opt_String(arr[3]),
      memoryType: dco_decode_String(arr[4]),
      visibility: dco_decode_String(arr[5]),
      createdAt: dco_decode_String(arr[6]),
      tags: dco_decode_list_String(arr[7]),
    );
  }

  @protected
  NetworkStats dco_decode_network_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NetworkStats(
      peerCount: dco_decode_u_32(arr[0]),
      dhtSize: dco_decode_u_32(arr[1]),
      isBootstrapped: dco_decode_bool(arr[2]),
      uptimeSecs: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  IdentityInfo? dco_decode_opt_box_autoadd_identity_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_identity_info(raw);
  }

  @protected
  ReplicationStatus dco_decode_replication_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ReplicationStatus(
      totalFragments: dco_decode_u_32(arr[0]),
      healthyFragments: dco_decode_u_32(arr[1]),
      repairingFragments: dco_decode_u_32(arr[2]),
      replicationFactor: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  IdentityInfo sse_decode_box_autoadd_identity_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_identity_info(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_avatarPath = sse_decode_opt_String(deserializer);
    var var_publicKeyHex = sse_decode_String(deserializer);
    var var_nodeIdHex = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return IdentityInfo(
      name: var_name,
      avatarPath: var_avatarPath,
      publicKeyHex: var_publicKeyHex,
      nodeIdHex: var_nodeIdHex,
      createdAt: var_createdAt,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemoryInfo> sse_decode_list_memory_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemoryInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_memory_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MemoryInfo sse_decode_memory_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_tesseraHash = sse_decode_String(deserializer);
    var var_mediaPath = sse_decode_String(deserializer);
    var var_context = sse_decode_opt_String(deserializer);
    var var_memoryType = sse_decode_String(deserializer);
    var var_visibility = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return MemoryInfo(
      hash: var_hash,
      tesseraHash: var_tesseraHash,
      mediaPath: var_mediaPath,
      context: var_context,
      memoryType: var_memoryType,
      visibility: var_visibility,
      createdAt: var_createdAt,
      tags: var_tags,
    );
  }

  @protected
  NetworkStats sse_decode_network_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerCount = sse_decode_u_32(deserializer);
    var var_dhtSize = sse_decode_u_32(deserializer);
    var var_isBootstrapped = sse_decode_bool(deserializer);
    var var_uptimeSecs = sse_decode_u_64(deserializer);
    return NetworkStats(
      peerCount: var_peerCount,
      dhtSize: var_dhtSize,
      isBootstrapped: var_isBootstrapped,
      uptimeSecs: var_uptimeSecs,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  IdentityInfo? sse_decode_opt_box_autoadd_identity_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_identity_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ReplicationStatus sse_decode_replication_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalFragments = sse_decode_u_32(deserializer);
    var var_healthyFragments = sse_decode_u_32(deserializer);
    var var_repairingFragments = sse_decode_u_32(deserializer);
    var var_replicationFactor = sse_decode_u_32(deserializer);
    return ReplicationStatus(
      totalFragments: var_totalFragments,
      healthyFragments: var_healthyFragments,
      repairingFragments: var_repairingFragments,
      replicationFactor: var_replicationFactor,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_identity_info(
    IdentityInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_identity_info(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.avatarPath, serializer);
    sse_encode_String(self.publicKeyHex, serializer);
    sse_encode_String(self.nodeIdHex, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_memory_info(
    List<MemoryInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_memory_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_memory_info(MemoryInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_String(self.tesseraHash, serializer);
    sse_encode_String(self.mediaPath, serializer);
    sse_encode_opt_String(self.context, serializer);
    sse_encode_String(self.memoryType, serializer);
    sse_encode_String(self.visibility, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_network_stats(NetworkStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.peerCount, serializer);
    sse_encode_u_32(self.dhtSize, serializer);
    sse_encode_bool(self.isBootstrapped, serializer);
    sse_encode_u_64(self.uptimeSecs, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_identity_info(
    IdentityInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_identity_info(self, serializer);
    }
  }

  @protected
  void sse_encode_replication_status(
    ReplicationStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.totalFragments, serializer);
    sse_encode_u_32(self.healthyFragments, serializer);
    sse_encode_u_32(self.repairingFragments, serializer);
    sse_encode_u_32(self.replicationFactor, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
