// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// User identity information (flat for FFI).
class IdentityInfo {
  final String name;
  final String? avatarPath;
  final String publicKeyHex;
  final String nodeIdHex;
  final String createdAt;

  const IdentityInfo({
    required this.name,
    this.avatarPath,
    required this.publicKeyHex,
    required this.nodeIdHex,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      avatarPath.hashCode ^
      publicKeyHex.hashCode ^
      nodeIdHex.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          avatarPath == other.avatarPath &&
          publicKeyHex == other.publicKeyHex &&
          nodeIdHex == other.nodeIdHex &&
          createdAt == other.createdAt;
}

/// Memory information returned to Flutter (flat for FFI).
class MemoryInfo {
  final String hash;
  final String tesseraHash;
  final String mediaPath;
  final String? context;
  final String memoryType;
  final String visibility;
  final String createdAt;
  final List<String> tags;
  final String? location;
  final List<String> people;
  final String language;
  final String mediaType;
  final String? sealedOpenAfter;
  final int? publicAfterDeathYears;

  const MemoryInfo({
    required this.hash,
    required this.tesseraHash,
    required this.mediaPath,
    this.context,
    required this.memoryType,
    required this.visibility,
    required this.createdAt,
    required this.tags,
    this.location,
    required this.people,
    required this.language,
    required this.mediaType,
    this.sealedOpenAfter,
    this.publicAfterDeathYears,
  });

  @override
  int get hashCode =>
      hash.hashCode ^
      tesseraHash.hashCode ^
      mediaPath.hashCode ^
      context.hashCode ^
      memoryType.hashCode ^
      visibility.hashCode ^
      createdAt.hashCode ^
      tags.hashCode ^
      location.hashCode ^
      people.hashCode ^
      language.hashCode ^
      mediaType.hashCode ^
      sealedOpenAfter.hashCode ^
      publicAfterDeathYears.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryInfo &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          tesseraHash == other.tesseraHash &&
          mediaPath == other.mediaPath &&
          context == other.context &&
          memoryType == other.memoryType &&
          visibility == other.visibility &&
          createdAt == other.createdAt &&
          tags == other.tags &&
          location == other.location &&
          people == other.people &&
          language == other.language &&
          mediaType == other.mediaType &&
          sealedOpenAfter == other.sealedOpenAfter &&
          publicAfterDeathYears == other.publicAfterDeathYears;
}

/// Network statistics (flat for FFI).
class NetworkStats {
  final int peerCount;
  final int dhtSize;
  final bool isBootstrapped;
  final BigInt uptimeSecs;
  final BigInt bytesTx;
  final BigInt bytesRx;

  const NetworkStats({
    required this.peerCount,
    required this.dhtSize,
    required this.isBootstrapped,
    required this.uptimeSecs,
    required this.bytesTx,
    required this.bytesRx,
  });

  @override
  int get hashCode =>
      peerCount.hashCode ^
      dhtSize.hashCode ^
      isBootstrapped.hashCode ^
      uptimeSecs.hashCode ^
      bytesTx.hashCode ^
      bytesRx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkStats &&
          runtimeType == other.runtimeType &&
          peerCount == other.peerCount &&
          dhtSize == other.dhtSize &&
          isBootstrapped == other.isBootstrapped &&
          uptimeSecs == other.uptimeSecs &&
          bytesTx == other.bytesTx &&
          bytesRx == other.bytesRx;
}

/// Connected peer information (flat for FFI).
class PeerInfo {
  final String nodeId;
  final String addr;

  const PeerInfo({required this.nodeId, required this.addr});

  @override
  int get hashCode => nodeId.hashCode ^ addr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerInfo &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          addr == other.addr;
}

/// Replication status (flat for FFI).
class ReplicationStatus {
  final int totalFragments;
  final int healthyFragments;
  final int repairingFragments;
  final int replicationFactor;

  const ReplicationStatus({
    required this.totalFragments,
    required this.healthyFragments,
    required this.repairingFragments,
    required this.replicationFactor,
  });

  @override
  int get hashCode =>
      totalFragments.hashCode ^
      healthyFragments.hashCode ^
      repairingFragments.hashCode ^
      replicationFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReplicationStatus &&
          runtimeType == other.runtimeType &&
          totalFragments == other.totalFragments &&
          healthyFragments == other.healthyFragments &&
          repairingFragments == other.repairingFragments &&
          replicationFactor == other.replicationFactor;
}

/// Storage statistics (flat for FFI).
class StorageStats {
  final BigInt totalBytes;
  final int tesseraCount;
  final int fragmentCount;

  const StorageStats({
    required this.totalBytes,
    required this.tesseraCount,
    required this.fragmentCount,
  });

  @override
  int get hashCode =>
      totalBytes.hashCode ^ tesseraCount.hashCode ^ fragmentCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageStats &&
          runtimeType == other.runtimeType &&
          totalBytes == other.totalBytes &&
          tesseraCount == other.tesseraCount &&
          fragmentCount == other.fragmentCount;
}
