[book]
title = "Guia do Usuário Tesseras"
authors = ["Colaboradores Tesseras"]
language = "pt-BR"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/book/pt-br/"
git-repository-url = "https://git.sr.ht/~ijanc/tesseras"
additional-css = ["theme/custom.css"]
smart-punctuation = true
default-theme = "light"
