// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_memory_type`, `parse_visibility`, `with_node`

/// Start the embedded node with the given data directory.
void nodeStart({required String dataDir}) =>
    RustLib.instance.api.crateApiSimpleNodeStart(dataDir: dataDir);

/// Stop the embedded node.
void nodeStop() => RustLib.instance.api.crateApiSimpleNodeStop();

/// Check if the node is currently running.
bool nodeIsRunning() => RustLib.instance.api.crateApiSimpleNodeIsRunning();

/// Create a user identity (profile).
IdentityInfo createIdentity({required String name, String? avatarPath}) =>
    RustLib.instance.api.crateApiSimpleCreateIdentity(
      name: name,
      avatarPath: avatarPath,
    );

/// Get the current user identity if one exists.
IdentityInfo? getIdentity() => RustLib.instance.api.crateApiSimpleGetIdentity();

/// Create a new memory (photo/video/text).
MemoryInfo createMemory({
  required String mediaPath,
  String? contextText,
  required String memoryType,
  required String visibility,
  String? locationDescription,
  double? locationLat,
  double? locationLon,
  required List<String> tags,
  required List<String> people,
  String? sealedOpenAfter,
  int? inactiveYears,
}) => RustLib.instance.api.crateApiSimpleCreateMemory(
  mediaPath: mediaPath,
  contextText: contextText,
  memoryType: memoryType,
  visibility: visibility,
  locationDescription: locationDescription,
  locationLat: locationLat,
  locationLon: locationLon,
  tags: tags,
  people: people,
  sealedOpenAfter: sealedOpenAfter,
  inactiveYears: inactiveYears,
);

/// Get timeline of memories with pagination.
List<MemoryInfo> getTimeline({required int offset, required int limit}) =>
    RustLib.instance.api.crateApiSimpleGetTimeline(
      offset: offset,
      limit: limit,
    );

/// Get a single memory by its content hash.
MemoryInfo getMemory({required String hash}) =>
    RustLib.instance.api.crateApiSimpleGetMemory(hash: hash);

/// Get current network statistics.
NetworkStats getNetworkStats() =>
    RustLib.instance.api.crateApiSimpleGetNetworkStats();

/// Get current replication status.
ReplicationStatus getReplicationStatus() =>
    RustLib.instance.api.crateApiSimpleGetReplicationStatus();

/// Get list of connected peers.
List<PeerInfo> getConnectedPeers() =>
    RustLib.instance.api.crateApiSimpleGetConnectedPeers();

/// Get storage statistics.
StorageStats getStorageStats() =>
    RustLib.instance.api.crateApiSimpleGetStorageStats();

/// Read a media blob by tessera hash, memory hash, and file name.
Uint8List getMediaBlob({
  required String tesseraHash,
  required String memoryHash,
  required String name,
}) => RustLib.instance.api.crateApiSimpleGetMediaBlob(
  tesseraHash: tesseraHash,
  memoryHash: memoryHash,
  name: name,
);
