//! Cross-crate compatibility test: verify that signatures generated by
//! pqcrypto-dilithium (C-based) can be verified by ml-dsa (pure Rust).
//!
//! ## Status: DEFERRED
//!
//! ML-DSA in tesseras-crypto is currently a placeholder (`mldsa: Option<()>`).
//! The native crate does not use pqcrypto-dilithium for signing — only
//! pqcrypto-kyber for KEM. There is no signing implementation to test against.
//!
//! Additionally, ml-dsa on crates.io is v0.1.0-rc.7 (pre-release).
//! Dilithium (CRYSTALS-Dilithium draft) != ML-DSA (FIPS 204 final) at the
//! byte level — NIST made changes during standardization.
//!
//! Decision: Ship WASM with Ed25519-only verification. ML-DSA verification
//! will be added when tesseras-crypto implements ML-DSA signing with the
//! pure Rust `ml-dsa` crate (or `fips204` 0.4.x) on both sides.
//!
//! See: docs/plans/2026-02-15-tesseras-wasm-design.md known risks.

// No tests to run — this file documents the compatibility investigation.
