[private]
default:
    @just --list --unsorted

# serve the site
serve:
    zola serve -i 0.0.0.0

# build the site
build:
    zola build

# deploy the site
deploy server="tesseras-website":
    ./deploy.sh {{ server }}
