[package]
name = "tesseras-storage"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tesseras-core = { workspace = true, features = ["service"] }
tesseras-crypto = { workspace = true, features = ["service"] }
serde = { workspace = true }
serde_json = { workspace = true }
rmp-serde = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
rusqlite = { workspace = true }
blake3 = { workspace = true }
toml = { workspace = true }
lru = { workspace = true }
fs2 = { workspace = true }
prometheus = { workspace = true }
tracing = { workspace = true }

[features]
default = []
bundled-sqlite = ["rusqlite/bundled"]

[dev-dependencies]
tempfile = { workspace = true }
filetime = "0.2"
proptest = { workspace = true }
