[package]
name = "tesseras-daemon"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "tesseras-daemon"
path = "src/main.rs"

[dependencies]
tesseras-core = { workspace = true, features = ["service"] }
tesseras-crypto = { workspace = true, features = ["classical", "service"] }
tesseras-storage = { workspace = true }
tesseras-net = { workspace = true }
tesseras-dht = { workspace = true }
tesseras-replication = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
hex = { workspace = true }
hickory-resolver = { workspace = true }
prometheus = { workspace = true }

[features]
default = []
bundled-sqlite = ["tesseras-storage/bundled-sqlite"]
